### ISSUE TITLE
Fix component scope/context confusion

### ISSUE THREAD

**Issue by phuu** [flightjs/flight#325]
A frequent source of bugs in Flight is the confusion about the scope and context of component methods, where a component instance can accidentally overwrite the state of another instance. It comes from how Flight builds components and instantiates them:

```js
function SomeComponent() {
 
  var counter = 0; // This is shared between all instances

  this.attributes({ ... });

  this.after('initialize', ...);

}
```

It gets even weirder with mixins, because the shared state will be per component that uses the mixin:

```js
function withX() {
  var beep = 'boop'; // one beep per component
}
```

This produces a bug in people's thinking and intuition of Flight code, which means bugs in actual code. It's avoidable if we change the way components are constructed such that the outer scope is run once per instance, rather than once per component.

My suggestion is to refactor Flight's `define` function to be simple function composition (left-to-right), so that each component is a function that can be run at instantiation time.

This also simplifies the `.mixin` method as it's just further composition.

I have a demo of this working already, but interested in other's thoughts.

**Comment by mikkotikkanen** [comment]
Yeah, this is a real problem. First solution would be to document properly how cases like this should be handled (ie. setting them as var's in main scope, as properties of this in initialize or in attributes?).

Best case scenario of course would be such implementation that it avoids issues like this.

**Comment by Mr0grog** [comment]
> so that each component is a function that can be run at instantiation time.

For what it’s worth, I’ve been experimenting with using mixins to add properties to to component types/constructors (rather than instances), so a change like this would break that. I imagine that’s not something very common, though, and I’m not even sure how well it will pan out for myself.

Example:
```javascript
function SomeComponentOrMixin() {
  this.constructor.something = function() {...};
}
```

**Comment by fridays** [comment]
What is the status on this?

Should I take it as a feature and make use of variables that are shared between component instances, or will this behaviour be removed in v2?

**Comment by giuseppeg** [comment]
@phuu +1 on this, your proposal sg2m too.

**Comment by salbertson** [comment]
@phuu I agree, changing the way components are constructed so that the outer scope is run once per instance, rather than once per component, would be great.

A team member and I quickly ran into issues using local variables in components. We were both surprised to find out they were shared across component instances.
