### ISSUE TITLE
Component instance API

### ISSUE THREAD

**Issue by phuu** [flightjs/flight#326]
`attachTo` currently doesn't return anything. This gives us an opportunity to create an API to add features.

```js
var instances = component.attachTo('.thing');
```

Things I'd like to see off the top of my head are:

- Teardown method. `instance.teardown()`
- Push new props. `instance.update(newProps)`
- Extensible by the component (web component, virtual DOM etc)

The last is interesting for me because a Flight component could actually be a way to create a Web Component.

```js
var component = define(FollowButton, withWebComponent('x-follow-button'))
var instance = component.attachTo('.follow-button', { user: '1234' });
// In the DOM: <x-follow-button class="follow-button" data-user="1234"></x-follow-button>

// Make things like this possible:
instance.node.addEventListener(...);
this.node.removeChild(instance.node); // Use it like a DOM node; causes teardown
```

Suggestions welcome!

**Comment by BugiDev** [comment]
Agree with @phuu . I have tried the `flight-with-child-component` mixin, and the first thing that I was missing was the instance of the child inside of the parent. I wanted to manipulate the child through the instance, instead of throwing the event and catching it. 

In case where i store some info of the children in parent and i know exactly which child i want to interact with, i don't need to create a listener and trigger an event, then check if that event is meant for that child, etc... It would be a lot easier if i could store the instance of the attached children and then just call a method on one child instance. 
This will also be good for the attachment of components. 

In some parent component:
```javascript
var childComponent = self.attachChild(SomeChildComponent, 'nodeToAttachChildTo', 
    {
         name: 'John Do',
         count: 3
     });
self.attr.childrenArray.push(childComponent);
```

And then, when i need to call some method of the child:
```javascript
self.attr.childrenArray[3].someMethod();
```

**Comment by phuu** [comment]
Thanks for your thoughts @BugiDev.

To clarify, I don't think the parent should have access to the methods of the child. Have a look at the [actor model](http://en.wikipedia.org/wiki/Actor_model) for some context about why.

I actually mean a very limited interface for talking/modifying to the child. The kind of thing that could simply be done with events.

@BugiDev Your example is troublesome because of the teardown behaviour — it has to work automatically. A parent cannot depend on a child being there (although the reverse can be true)

**Comment by necolas** [comment]
I felt that something like this was missing too, and ended up playing around with hacks like http://codepen.io/necolas/pen/Djbpr to get the desired outcome.

**Comment by tbrd** [comment]
I like the idea of being able to teardown a component from the parent. We do this anyway with events - would seem sensible to provide a simple API for that.

**Comment by giuseppeg** [comment]
Wouldn't this go against the principle of separation of concerns?

<blockquote>Flight enforces strict separation of concerns. When you create a component you don't get a handle to it. Consequently, components cannot be referenced by other components and cannot become properties of the global object tree. This is by design. Components do not engage each other directly</blockquote>

What would happen when

* the child component is torn down
* your try to do something with the instance

@tbrd with events instead the child components teardown themselves in case they are still around

**Comment by phuu** [comment]
Hmm. It's a tough question. Here's my thinking behind this; perhaps it'll clarify why I want it (though there aren't really any answers here).

In short(ish), I don't really think the actor model (aka, Flight-philosophy) is really suitable for building complex interfaces, and Flight throws the baby out with the bath water in it's insistence separating components from each other. 

React and cousins have shown there's a huge amount of value in accepting component hierarchy, and I think there's a comfortable middle ground for Flight.

Perhaps this will make more sense when TweetDeck open-sources the observable stream stuff we've been using — it's absolutely staggering how much more simple, testable and readable components become when you architect for the inherent tree-structure of UI.

It's possible we don't need this, but I'd be really interested to discuss it.

**Comment by ahume** [comment]
We need to get the observable stuff out so it can help inform this, but the mixins we have created would arguably benefit from having more direct knowledge of their parent/child relations (it would remove some boilerplate that we're using withResource for). Let's try and get a version of that out next week.

**Comment by giuseppeg** [comment]
@phuu I hear you but that's one of the best features of flight in my opinion.
Maybe we can improve `withChildComponents` to solve some of those problems.

For example we could add a `children registry` where we store some info about children components,
push stuff on it when we use `this.attachChild` and have `this.attachChild` return a `ChildComponent` object that exposes the API you suggested ie. you get instance info only from `this.attachChild` instead of `Component.attachTo`.

`this.attachChild` would mix an object in the child component so that after teardown we can remove the child from the parent's registry.
`ChildComponent` would have access to the children registry of course.

I also suggest to introduce a new concept of `RootComponent|ComponentsGroup|FlightSquares` :) or something like that so that people understand that components that get withChildComponents are just a common place where you can organise the subtree and establish those relationships - at yelp we call them `controllers`

**Comment by giuseppeg** [comment]
The other day I realized that the idea above is implemented in Deku (a component-based framework from Segment). They call these thing Scene(s) https://github.com/segmentio/deku/wiki/Scene-API

**Comment by ehtb** [comment]
I was playing with the idea to add some component hierarchy to my app. I like how React solves the inverse data flow and the idea of passing callbacks as props / attributes to the child components.

To test this on Flight, all I had to do was remove these three lines:
https://github.com/flightjs/flight/blob/master/lib/base.js#L84

This removes the ability to call a function in ```this.attributes```, but it enables me to do stuff like:

```
this.attachChild(Playlist, this.select('playlistSelector'), {
 onSongClick: this.onSongClick.bind(this)
});
```

For me the challenge now, is how to share state with the child components. On an individual component level you can add state through ```with-state```, but it would be great to update the child component's attributes through a React like function ```render``` without a need for a virtual dom (which is my use case for using Flight).  

IMO state would be a inherent part of Flight. Children could only be initialised through ```attachChild``` and pushed into an array. When the parent state is updated, a method like ```this.afterStateChanged``` would be invoked on the child.
