### ISSUE TITLE
Use Element.prototype.closest when supported

### ISSUE THREAD

**Issue by giuseppeg** [flightjs/flight#361]
`dom.closest` should use `Element.prototype.closest` when supported. [[PR Comment](https://github.com/flightjs/flight/pull/358/files#diff-957520c0f46b971206faac53f37127b8R242)]

**Comment by phuu** [comment]
This is a fiddly one — we definitely should. I'm not really sure how to test it — I'd rather not force `closest` use the built-in in browsers that support it, so that the Flight implementation is used, because it would make the tests leak into the function.

Maybe as a compromise we could expose the Flight implementation as `flightClosest` (and not mention it), test that function, and then make `closest` a feature-detector and not test it.

What do you think?

**Comment by giuseppeg** [comment]
I think we have two options here:

1) we start to polyfill a whole bunch of stuff (not to excited about this)
2) we suggest to use or we find a way to bundle [FT's polyfills](cdn.polyfill.io) with flight - no tests required form our end

http://git.io/vO3gc

**Comment by phuu** [comment]
Oh, that's an interesting approach, and there might be other polyfills we could use (CustomEvent?) for all the stuff that's soon to be standardised. What do you think about coming up with a baseline browser feature-set for Flight? (We already require es5-shim, I think)

**Comment by giuseppeg** [comment]
sg2m, we'll have to figure out how to make standalone builds from their repo and maybe deploy it in a separate repo under the flightjs org. Would you keep es5-shim or should we include its shims in the Flight bundle?

btw yes they have polyfills for all the ± new features, CustomEvent included.

**Comment by phuu** [comment]
I was thinking we just declare a baseline and ask users to deliver that however they like — what do you think of that?

**Comment by giuseppeg** [comment]
I like that :shipit:

**Comment by phuu** [comment]
v2 thing — will close this. Maybe someone in future will come back and work on Flight 2!
